# Site settings
title: Redstone.dart
name: Redstone.dart
email: luiz.mineo@gmail.com
description: "Redstone.dart website"
baseurl: ""
url: "http://redstonedart.org"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty

collections:
  doc:
    output: true
